# coding: utf-8


tagset_nltk = {'"': ('closing-quotation-mark', 'Closing quotation mark'),
               '$': ('dollar', 'Dollar'),
               '(': ('opening-parenthesis', 'Opening parenthesis'),
               ')': ('closing-parenthesis', 'Closing parenthesis'),
               '--': ('dash', 'Dash'),
               '.': ('sentence-terminator', 'Sentence terminator'),
               '0': ('comma', 'Comma'),
               ':': ('colon-or-ellipsis', 'Colon or ellipsis'),
               'CC': ('conjunction-coordinating', 'Conjunction, coordinating'),
               'CD': ('numeral-cardinal', 'Numeral, cardinal'),
               'DT': ('determiner', 'Determiner'),
               'EX': ('existential-there', 'Existential there'),
               'FW': ('foreign-word', 'Foreign word'),
               'IN': ('preposition-or-conjunction-subordinating',
                      'Preposition or conjunction, subordinating'),
               'JJ': ('adjective-or-numeral-ordinal',
                      'Adjective or numeral, ordinal'),
               'JJR': ('adjective-comparative', 'Adjective, comparative'),
               'JJS': ('adjective-superlative', 'Adjective, superlative'),
               'LS': ('list-item-marker', 'List item marker'),
               'MD': ('modal-auxiliary', 'Modal auxiliary'),
               'NN': ('noun-common-singular-or-mass',
                      'Noun, common, singular or mass'),
               'NNP': ('noun-proper-singular', 'Noun, proper, singular'),
               'NNPS': ('noun-proper-plural', 'Noun, proper, plural'),
               'NNS': ('noun-common-plural', 'Noun, common, plural'),
               'NP': ('noun-proper-singular', 'Noun, proper, singular'),
               'NPS': ('noun-proper-plural', 'Noun, proper, plural'),
               'PDT': ('pre-determiner', 'Pre-determiner'),
               'POS': ('genitive-marker', 'Genitive marker'),
               'PP': ('pronoun-personal', 'Pronoun, personal'),
               'PP$': ('pronoun-possessive', 'Pronoun, possessive'),
               'PRP': ('pronoun-personal', 'Pronoun, personal'),
               'PRP$': ('pronoun-possessive', 'Pronoun, possessive'),
               'RB': ('adverb', 'Adverb'),
               'RBR': ('adverb-comparative', 'Adverb, comparative'),
               'RBS': ('adverb-superlative', 'Adverb, superlative'),
               'RP': ('particle', 'Particle'),
               'SYM': ('symbol', 'Symbol'),
               'TO': ('to-as-preposition-or-infinitive-marker',
                      '"to" as preposition or infinitive marker'),
               'UH': ('interjection', 'Interjection'),
               'VB': ('verb-base-form', 'Verb, base form'),
               'VBD': ('verb-past-tense', 'Verb, past tense'),
               'VBG': ('verb-present-participle-or-gerund',
                       'Verb, present participle or gerund'),
               'VBN': ('verb-past-participle', 'Verb, past participle'),
               'VBP': ('verb-present-tense-not-3rd-person-singular',
                       'Verb, present tense, not 3rd person singular'),
               'VBZ': ('verb-present-tense-3rd-person-singular',
                       'Verb, present tense, 3rd person singular'),
               'WDT': ('wh-determiner', 'Wh-determiner'),
               'WP': ('wh-pronoun', 'Wh-pronoun'),
               'WP$': ('wh-pronoun-possessive', 'Wh-pronoun, possessive'),
               'WRB': ('wh-adverb', 'Wh-adverb'),
               '``': ('opening-quotation-mark', 'Opening quotation mark'),
}
