# coding: utf-8
#
# Copyright 2012 NAMD-EMAP-FGV
#
# This file is part of PyPLN. You can get more information at: http://pypln.org/.
#
# PyPLN is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PyPLN is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PyPLN.  If not, see <http://www.gnu.org/licenses/>.

LANGUAGES = dict([('en', 'English'),
                  ('da', 'Danish'),
                  ('nl', 'Dutch'),
                  ('fi', 'Finnish'),
                  ('fr', 'French'),
                  ('de', 'German'),
                  ('he', 'Hebrew'),
                  ('it', 'Italian'),
                  ('ja', 'Japanese'),
                  ('ko', 'Korean'),
                  ('nb', 'Norwegian'),
                  ('pl', 'Polish'),
                  ('pt', 'Portuguese'),
                  ('ru', 'Russian'),
                  ('es', 'Spanish'),
                  ('sv', 'Swedish'),
                  ('zh', 'Chinese'),
                  ('cs', 'Czech'),
                  ('el', 'Greek'),
                  ('is', 'Icelandic'),
                  ('lv', 'Latvian'),
                  ('lt', 'Lithuanian'),
                  ('ro', 'Romanian'),
                  ('hu', 'Hungarian'),
                  ('et', 'Estonian'),
                  ('ut', 'Tg unknown language'),
                  ('un', 'Unknown'),
                  ('bg', 'Bulgarian'),
                  ('hr', 'Croatian'),
                  ('sr', 'Serbian'),
                  ('ga', 'Irish'),
                  ('gl', 'Galician'),
                  ('fil', 'Tagalog'),
                  ('tr', 'Turkish'),
                  ('uk', 'Ukrainian'),
                  ('hi', 'Hindi'),
                  ('mk', 'Macedonian'),
                  ('bn', 'Bengali'),
                  ('id', 'Indonesian'),
                  ('la', 'Latin'),
                  ('ms', 'Malay'),
                  ('ml', 'Malayalam'),
                  ('cy', 'Welsh'),
                  ('ne', 'Nepali'),
                  ('te', 'Telugu'),
                  ('sq', 'Albanian'),
                  ('ta', 'Tamil'),
                  ('be', 'Belarusian'),
                  ('jw', 'Javanese'),
                  ('oc', 'Occitan'),
                  ('ur', 'Urdu'),
                  ('bh', 'Bihari'),
                  ('gu', 'Gujarati'),
                  ('th', 'Thai'),
                  ('ar', 'Arabic'),
                  ('ca', 'Catalan'),
                  ('eo', 'Esperanto'),
                  ('eu', 'Basque'),
                  ('ia', 'Interlingua'),
                  ('kn', 'Kannada'),
                  ('pa', 'Punjabi'),
                  ('gd', 'Scots gaelic'),
                  ('sw', 'Swahili'),
                  ('sl', 'Slovenian'),
                  ('mr', 'Marathi'),
                  ('mt', 'Maltese'),
                  ('vi', 'Vietnamese'),
                  ('fy', 'Frisian'),
                  ('sk', 'Slovak'),
                  ('zh-TW', 'Chineset'),
                  ('fo', 'Faroese'),
                  ('su', 'Sundanese'),
                  ('uz', 'Uzbek'),
                  ('am', 'Amharic'),
                  ('az', 'Azerbaijani'),
                  ('ka', 'Georgian'),
                  ('ti', 'Tigrinya'),
                  ('fa', 'Persian'),
                  ('bs', 'Bosnian'),
                  ('si', 'Sinhalese'),
                  ('nn', 'Norwegian n'),
                  ('pt-PT', 'Portuguese (Portugal)'),
                  ('pt-BR', 'Portuguese (Brazil)'),
                  ('xh', 'Xhosa'),
                  ('zu', 'Zulu'),
                  ('gn', 'Guarani'),
                  ('st', 'Sesotho'),
                  ('tk', 'Turkmen'),
                  ('ky', 'Kyrgyz'),
                  ('br', 'Breton'),
                  ('tw', 'Twi'),
                  ('yi', 'Yiddish'),
                  ('sh', 'Serbo croatian'),
                  ('so', 'Somali'),
                  ('ug', 'Uighur'),
                  ('ku', 'Kurdish'),
                  ('mn', 'Mongolian'),
                  ('hy', 'Armenian'),
                  ('lo', 'Laothian'),
                  ('sd', 'Sindhi'),
                  ('rm', 'Rhaeto romance'),
                  ('af', 'Afrikaans'),
                  ('lb', 'Luxembourgish'),
                  ('my', 'Burmese'),
                  ('km', 'Khmer'),
                  ('bo', 'Tibetan'),
                  ('dv', 'Dhivehi'),
                  ('chr', 'Cherokee'),
                  ('syr', 'Syriac'),
                  ('sit-NP', 'Limbu'),
                  ('or', 'Oriya'),
                  ('as', 'Assamese'),
                  ('co', 'Corsican'),
                  ('ie', 'Interlingue'),
                  ('kk', 'Kazakh'),
                  ('ln', 'Lingala'),
                  ('mo', 'Moldavian'),
                  ('ps', 'Pashto'),
                  ('qu', 'Quechua'),
                  ('sn', 'Shona'),
                  ('tg', 'Tajik'),
                  ('tt', 'Tatar'),
                  ('to', 'Tonga'),
                  ('yo', 'Yoruba'),
                  ('cpe', 'Creoles and pidgins english based'),
                  ('cpf', 'Creoles and pidgins french based'),
                  ('cpp', 'Creoles and pidgins portuguese based'),
                  ('crp', 'Creoles and pidgins other'),
                  ('mi', 'Maori'),
                  ('wo', 'Wolof'),
                  ('ab', 'Abkhazian'),
                  ('aa', 'Afar'),
                  ('ay', 'Aymara'),
                  ('ba', 'Bashkir'),
                  ('bi', 'Bislama'),
                  ('dz', 'Dzongkha'),
                  ('fj', 'Fijian'),
                  ('kl', 'Greenlandic'),
                  ('ha', 'Hausa'),
                  ('ht', 'Haitian creole'),
                  ('ik', 'Inupiak'),
                  ('iu', 'Inuktitut'),
                  ('ks', 'Kashmiri'),
                  ('rw', 'Kinyarwanda'),
                  ('mg', 'Malagasy'),
                  ('na', 'Nauru'),
                  ('om', 'Oromo'),
                  ('rn', 'Rundi'),
                  ('sm', 'Samoan'),
                  ('sg', 'Sango'),
                  ('sa', 'Sanskrit'),
                  ('ss', 'Siswant'),
                  ('ts', 'Tsonga'),
                  ('tn', 'Tswana'),
                  ('vo', 'Volapuk'),
                  ('za', 'Zhuang'),
                  ('kha', 'Khasi'),
                  ('sco', 'Scots'),
                  ('lg', 'Ganda'),
                  ('gv', 'Manx'),
                  ('sr-ME', 'Montenegrin')])
