# coding: utf-8
#
# Copyright 2012 NAMD-EMAP-FGV
#
# This file is part of PyPLN.
#
# PyPLN is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PyPLN is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PyPLN.  If not, see <http://www.gnu.org/licenses/>.

TAGSET = {
        '$': {'color': '#00CC33', 'label': u'Dollar', 'slug': 'dollar'},
        "''": {'color': '#000066',
         'label': u'Closing quotation mark',
         'slug': 'closing-quotation-mark'},
        '(': {'color': '#0099FF',
         'label': u'Opening parenthesis',
         'slug': 'opening-parenthesis'},
        ')': {'color': '#FFFF66',
         'label': u'Closing parenthesis',
         'slug': 'closing-parenthesis'},
        ',': {'color': '#009999', 'label': u'Comma', 'slug': 'comma'},
        '.': {'color': '#00AAAA', 'label': u'Dot', 'slug': 'dot'},
        '--': {'color': '#003333', 'label': u'Dash', 'slug': 'dash'},
        '0': {'color': '#009966',
         'label': u'Sentence terminator',
         'slug': 'sentence-terminator'},
        ':': {'color': '#0066CC',
         'label': u'Colon or ellipsis',
         'slug': 'colon-or-ellipsis'},
        'CC': {'color': '#0033FF',
         'label': u'Conjunction, coordinating',
         'slug': 'conjunction-coordinating'},
        'CD': {'color': '#003399',
         'label': u'Numeral, cardinal',
         'slug': 'numeral-cardinal'},
        'DT': {'color': '#000033', 'label': u'Determiner', 'slug': 'determiner'},
        'EX': {'color': '#FF9900',
         'label': u'Existential there',
         'slug': 'existential-there'},
        'FW': {'color': '#00FF99', 'label': u'Foreign word', 'slug': 'foreign-word'},
        'IN': {'color': '#FF6666',
         'label': u'Preposition or conjunction, subordinating',
         'slug': 'preposition-or-conjunction-subordinating'},
        'JJ': {'color': '#00CCFF',
         'label': u'Adjective or numeral, ordinal',
         'slug': 'adjective-or-numeral-ordinal'},
        'JJR': {'color': '#0000FF',
         'label': u'Adjective, comparative',
         'slug': 'adjective-comparative'},
        'JJS': {'color': '#003300',
         'label': u'Adjective, superlative',
         'slug': 'adjective-superlative'},
        'LS': {'color': '#FFCC66',
         'label': u'List item marker',
         'slug': 'list-item-marker'},
        'MD': {'color': '#FF6633',
         'label': u'Modal auxiliary',
         'slug': 'modal-auxiliary'},
        'NN': {'color': '#00CC00',
         'label': u'Noun, common, singular or mass',
         'slug': 'noun-common-singular-or-mass'},
        'NNP': {'color': '#006666',
         'label': u'Noun, proper, singular',
         'slug': 'noun-proper-singular'},
        'NNPS': {'color': '#FF6600',
         'label': u'Noun, proper, plural',
         'slug': 'noun-proper-plural'},
        'NNS': {'color': '#006699',
         'label': u'Noun, common, plural',
         'slug': 'noun-common-plural'},
        'NP': {'color': '#0066FF',
         'label': u'Noun, proper, singular',
         'slug': 'noun-proper-singular'},
        'NPS': {'color': '#000099',
         'label': u'Noun, proper, plural',
         'slug': 'noun-proper-plural'},
        'PDT': {'color': '#0033CC',
         'label': u'Pre-determiner',
         'slug': 'pre-determiner'},
        'POS': {'color': '#FFFF33',
         'label': u'Genitive marker',
         'slug': 'genitive-marker'},
        'PP': {'color': '#000000',
         'label': u'Pronoun, personal',
         'slug': 'pronoun-personal'},
        'PP$': {'color': '#FFCC00',
         'label': u'Pronoun, possessive',
         'slug': 'pronoun-possessive'},
        'PRP': {'color': '#009933',
         'label': u'Pronoun, personal',
         'slug': 'pronoun-personal'},
        'PRP$': {'color': '#00FFFF',
         'label': u'Pronoun, possessive',
         'slug': 'pronoun-possessive'},
        'RB': {'color': '#009900', 'label': u'Adverb', 'slug': 'adverb'},
        'RBR': {'color': '#FF9933',
         'label': u'Adverb, comparative',
         'slug': 'adverb-comparative'},
        'RBS': {'color': '#FF9966',
         'label': u'Adverb, superlative',
         'slug': 'adverb-superlative'},
        'RP': {'color': '#00CC66', 'label': u'Particle', 'slug': 'particle'},
        'SYM': {'color': '#0000CC', 'label': u'Symbol', 'slug': 'symbol'},
        'TO': {'color': '#FFFF00',
         'label': u'"to" as preposition or infinitive marker',
         'slug': 'to-as-preposition-or-infinitive-marker'},
        'UH': {'color': '#FF3366', 'label': u'Interjection', 'slug': 'interjection'},
        'VB': {'color': '#FFCC33',
         'label': u'Verb, base form',
         'slug': 'verb-base-form'},
        'VBD': {'color': '#0099CC',
         'label': u'Verb, past tense',
         'slug': 'verb-past-tense'},
        'VBG': {'color': '#00FFCC',
         'label': u'Verb, present participle or gerund',
         'slug': 'verb-present-participle-or-gerund'},
        'VBN': {'color': '#00FF66',
         'label': u'Verb, past participle',
         'slug': 'verb-past-participle'},
        'VBP': {'color': '#00FF33',
         'label': u'Verb, present tense, not 3rd person singular',
         'slug': 'verb-present-tense-not-3rd-person-singular'},
        'VBZ': {'color': '#00CC99',
         'label': u'Verb, present tense, 3rd person singular',
         'slug': 'verb-present-tense-3rd-person-singular'},
        'WDT': {'color': '#00FF00',
         'label': u'Wh-determiner',
         'slug': 'wh-determiner'},
        'WP': {'color': '#00CCCC', 'label': u'Wh-pronoun', 'slug': 'wh-pronoun'},
        'WP$': {'color': '#003366',
         'label': u'Wh-pronoun, possessive',
         'slug': 'wh-pronoun-possessive'},
        'WRB': {'color': '#006600', 'label': u'Wh-adverb', 'slug': 'wh-adverb'},
        '``': {'color': '#006633',
         'label': u'Opening quotation mark',
         'slug': 'opening-quotation-mark'},
        '#': {'color': '#CCCCCC', 'label': 'Hash', 'slug': 'hash'},
        '-NONE-': {'color': '#DDDDDD', 'label': 'None', 'slug': 'none'},
}

COMMON_TAGS = [u'NNP', u'NN', u'CD', u'IN', u':', u'JJ', u'DT', u',', u'NNS',
        u'CC', u"''", u'VBZ', u'VBN', u'.', u'RB', u'#', u'TO', u'VB', u'VBG',
        u'VBP', u'VBD', u'MD', u'PRP', u'WDT', u'POS', u'PRP$', u'-NONE-',
        u'JJR', u'WRB', u'NNPS', u'JJS', u'EX', u'WP', u'``', u'RP', u'RBR',
        u'RBS', u'WP$', u'$', u'LS']
